=== Digital-Media/wef1vo-examples/vo07/xml/rezept.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rezept">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gericht"/>
                <xs:element ref="zutaten"/>
                <xs:element ref="zubereitung"/>
            </xs:sequence>
            <xs:attribute name="quelle" type="xs:anyURI" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="gericht" type="xs:string"/>

    <xs:element name="zutaten">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="zutat"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="zubereitung">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="schritt" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="zutat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ingredienz" type="xs:string"/>
                <xs:element name="menge" type="xs:decimal"/>
                <xs:element name="einheit" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Digital-Media/wef1vo-examples/vo07/xml/tiroler_knoedel_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rezept xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://www.hochleitner.cc/schemas/rezept.xsd"
        quelle="https://www.ichkoche.at/der-klassische-tiroler-knoedel-rezept-4386">
    <gericht>Der klassische Tiroler Knödel</gericht>
    <zutaten>
        <zutat>
            <ingredienz>Semmelwürfel</ingredienz>
            <menge>350</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat>
            <ingredienz>Milch</ingredienz>
            <menge>200</menge>
            <einheit>ml</einheit>
        </zutat>
        <zutat>
            <ingredienz>Eier</ingredienz>
            <menge>4</menge>
            <einheit>Stück</einheit>
        </zutat>
        <zutat>
            <ingredienz>Speck</ingredienz>
            <menge>100</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat>
            <ingredienz>Bergsteigerwurst</ingredienz>
            <menge>100</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat>
            <ingredienz>Butter</ingredienz>
            <menge>20</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat>
            <ingredienz>Zwiebel</ingredienz>
            <menge>1</menge>
            <einheit>Stück</einheit>
        </zutat>
        <zutat>
            <ingredienz>Petersilie</ingredienz>
            <menge>10</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat>
            <ingredienz>Salz</ingredienz>
            <menge>1</menge>
            <einheit>Prise</einheit>
        </zutat>
        <zutat>
            <ingredienz>Muskatnuss</ingredienz>
            <menge>1</menge>
            <einheit>Prise</einheit>
        </zutat>
        <zutat>
            <ingredienz>Mehl</ingredienz>
            <menge>80</menge>
            <einheit>g</einheit>
        </zutat>
        <zutat>
            <ingredienz>Schnittlauch</ingredienz>
            <menge>10</menge>
            <einheit>g</einheit>
        </zutat>
    </zutaten>
    <zubereitung>
        <schritt>Semmelwürfel mit Milch und Eiern vermengen und 20 bis 30 Minuten ziehen lassen.</schritt>
        <schritt>Kleinwürfelig geschnittenen Speck und fein gewiegte Bergsteigerwurst in zerlassener Butter gemeinsam
            mit Zwiebeln, Petersilie und Schnittlauch anbraten und mit Salz und Muskatnuss abschmecken. Mehl darüber
            streuen und aus allen Zutaten eine feste, aber nicht zu feuchte Masse kneten.
        </schritt>
        <schritt>Mit befeuchteten Händen daraus Knödel formen.</schritt>
        <schritt>Einen davon als Probeknödel in Salzwasser knappe 15 Minuten kochen. Hat der Probeknödel eine zu weiche
            Konsistenz, muss man noch etwas Mehl unter die Knödelmasse kneten.
        </schritt>
        <schritt>Erst wenn die Masse kompakt genug ist, kocht man die restlichen Knödel.</schritt>
        <schritt>Tiroler Knödel mit Schnittlauch bestreut servieren.</schritt>
    </zubereitung>
</rezept>
